import {IHashMap} from "./app.hashmap";
import {DisasmOffset} from "./app.disasmoffset";
import {PerformanceSimulationMetric} from "./app.performancesimulationmetric";

export class TraceResult {
  public traceName: string;
  public publicationDate: string;
  public application: string;
  public threadCount: number;
  public workload: string;
  public component: string;
  public componentVersion: string;
  public operativeSystem: string;
  public compiler: string;
  public segment: string;
  public classification: string;
  public tracePath: string;
  public userInstructionPercentage: number;
  public kernelInstructionPercentage: number;
  public instructionWeight: number;
  public cycleWeight: number;
  public userInstructionCount: number;
  public kernelInstructionCount: number;
  public totalInstructionCount: number;
  public instructionsRepresented: number;
  public cyclesRepresented: number;
  public isCr3SharedAmongThreads: boolean;
  public cr3SharedData: string[];
  public hasLockInstructions: boolean;
  public lockInstructions: string[];
  public lcatimpact: string;
  public hasLCATData: boolean;
  public studyLists: string[];
  public emonConfigurations: string[];
  public traceLists: string[];
  public isas: IHashMap;
  public iforms: IHashMap;
  public categories: IHashMap;
  public isaSets: IHashMap;
  public instructions: IHashMap;
  public performanceSimulationMetrics: PerformanceSimulationMetric[];
  public keikoStats: PerformanceSimulationMetric[];
  public funcionalMetrics: IHashMap;
  public hsd: number;
  public machine: string;
  public invalidFields: string;
  public disasmOffset: DisasmOffset;
  public published: boolean;
  public preproduction: boolean;
  public isaPercentage:number;
  public traceNameWithoutSuffix: string;
}
